### ISSUE TITLE
The STATICFILES_DIRS setting should not contain the STATIC_ROOT setting.

### ISSUE THREAD

**Issue by cuparanalytics** [Azure-Samples/msdocs-python-django-webapp-quickstart#10]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
deploy the app: git push azure main:master 

### Any log messages given by the failure
remote: ERRORS:
remote: ?: (staticfiles.E002) The STATICFILES_DIRS setting should not contain the STATIC_ROOT setting.

### Expected/desired behavior
No errors on deployment.

### OS and Version?
Windows 11. 

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by vmagelo** [comment]
Thanks for pointing this out. Addressed in https://github.com/Azure-Samples/msdocs-python-django-webapp-quickstart/pull/14
