### ISSUE TITLE
Static files are not loading at all on local development 

### ISSUE THREAD

**Issue by ifirdavs** [Azure-Samples/msdocs-python-django-webapp-quickstart#18]
![image](https://github.com/Azure-Samples/msdocs-python-django-webapp-quickstart/assets/101515354/d50d8070-ff1b-4fe7-b25c-6948502c4d8d)
![image](https://github.com/Azure-Samples/msdocs-python-django-webapp-quickstart/assets/101515354/e7c47601-409e-4c07-8027-acf7fe490ae9)

**Comment by fismoilov20** [comment]
# [SOLVED]
vmagelo updated settings.py recently:
![image](https://github.com/Azure-Samples/msdocs-python-django-webapp-quickstart/assets/101515354/831c7941-9496-45f0-a74d-97614d3a0a3c)
Remove the line "whitenoise.runserver_nostatic".
